### ISSUE TITLE
javassist书写技巧

### ISSUE THREAD

**Issue by tanzhou2002** [PPPHUANG/rpc-spring-starter#1]
请问大佬，您在编写ProxyFactory这个类时，编写javassist相关代码时，是先写好假想的代码，然后再用 javassist去拼接吗？我代码虽然可以看得懂，但是自己很难写出来，关于这个javassist代码编写 大佬有相关技巧分享吗？

**Comment by PPPHUANG** [comment]
哈哈哈，没什么技巧。先写好自己想生成的类，然后再使用 javassist 一点一点拼接，不断 debug 直到生成想要的类

**Comment by tanzhou2002** [comment]
好的 我写的有点痛苦
