### ISSUE TITLE
zookeeper端口修改

### ISSUE THREAD

**Issue by tanzhou2002** [PPPHUANG/rpc-spring-starter#2]
大佬，zookeeper默认不是 2181端口吗？ 项目中为啥要设置为 2128啊？

**Comment by PPPHUANG** [comment]
能用默认端口的情况很少，比如你一个部署zk的机器部署了两个节点，肯定有一个端口不是2181，不需要纠结这个的。

**Comment by tanzhou2002** [comment]
哦哦 明白了
